language: node_js
node_js:
    - "6"
    - "5"
    - "4"
script:
    - npm test
    - npm run build

after_success:
    - bash <(curl -s https://codecov.io/bash)
after_script:
    - npm run test:cover
    - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

notifications:
  email: false

# whitelist
branches:
  only:
    - master
