language: node_js
node_js:
    - "6"
    - "5"
    - "4"
script:
    - npm test
    - npm run build
after_script:
    - npm run test:cover
    - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

# whitelist
branches:
  only:
    - master
